trigger:
  branches:
    include:
      -develop
    exclude:
      -main
      -master



pool:
 vmImage: 'ubuntu-latest' # Exécuter sur une VM Ubuntu

jobs:
  - job: Build
    variables: tpfinal-vars
  - group: 'cours-framework-dev'
    steps:
    - template: ./templates/_build-front.yml