name: Build and Deploy to Azure
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image
      run: |
        docker build --build-arg BUILD_ID=${{ github.sha }} -t monapp ./mon-app
        docker tag monapp ${{ secrets.DOCKERHUB_USERNAME }}/mon-app:${{ github.sha }}
        docker tag monapp ${{ secrets.DOCKERHUB_USERNAME }}/mon-app:latest
    
    - name: Push Docker image
      run: | 
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-app:${{ github.sha}}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-app:latest
  deploy:
    needs: build
    if: github.event_name == "push"
    runs-on : ubuntu-latest
    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: mon-app-container
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/mon-app:${{ github.sha }}
      - name: Afficher dans le résumé du job l'URL
        run: 
          echo "Réussi !" $GITHUB_STEP_SUMMARY
          echo "Lien app  https://mon-app-container.azurewebsites.net" $GITHUB_STEP_SUMMARY
          
